@startuml
interface Anulador {
    +activar(): void
    +puntosLuegoDeEvaluacion(puntajeNoAnulado: int, jugadoresQueUsaronAnulador: ArrayList<Jugador>,unJugador:Jugador): int
}


class Pregunta {
    - String: enunciado
    - ArrayList: respuestas

    +{static}Pregunta(String: enunciado, ArrayList: respuestas, FormaDePuntuar: tipoDePregunta)
    + puntuar(ArrayList: respuestas, Jugador: unJugador)
    + respuestasPosibles() ArrayList: respuestas
    + getEnunciado() String: enunciado
}


@enduml
