@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam classAttributeIconSize 0
skinparam monochrome true

class Jugador{
    +activarExclusividad(this)
}

class Pregunta{
    -jugadoresQueActivaronExclusividad: Array<Jugador>
    +activarExclusividad(jugador: Jugador)
}
Jugador .> Pregunta

Pregunta -> Exclusividad


class Exclusividad{

}
Exclusividad o-> EstadoExclusividad

interface EstadoExclusividad {

}

class ExclusividadActivado implements EstadoExclusividad{
    puntuar()
}

class ExclusividadDesctivado implements EstadoExclusividad{

}
note right
+puntuar()
 //no hace nada
end note
@enduml