@startuml
'https://plantuml.com/class-diagram'
hide circle
skinparam classAttributeIconSize 0
skinparam monochrome true

class Jugador {

nombre+ responder(respuesta : String):
}

class Panel {

}

class GeneradorDePreguntas{

    + generarPregunta():
}

class AlgoJuego{

}

interface Pregunta {
    -obtenerRespuestaCorrecta(): Array<Respuesta>
    + puntuar(respuesta : Respuesta)
}

interface ModficadorDePuntaje {
    + method():
}


interface Bonificacador {
    + method():
}

interface Penalizacion {
    + method():
}

class VerdaderoFalsoClasico {

}

class VerdaderoFalsoPenalidad {

}

class MultipleChoiceClasico {

}

class MultipleChoiceParcial {

}

class MultipleChoicePenalidad {

}

class OrderedChoice {

}

class GroupChoice {

}

interface PenalizacionPregunta {

}

class Respuesta{
    +esCorrecta(): Boolean+ method():
}

class RespuestaElegida{

}


ModficadorDePuntaje <|.. Bonificacador
ModficadorDePuntaje <|.. Penalizacion


AlgoJuego -- Jugador
AlgoJuego-- GeneradorDePreguntas
Panel --> Pregunta
Pregunta *-"*"Respuesta

Pregunta <|.. VerdaderoFalsoClasico
Pregunta <|.. VerdaderoFalsoPenalidad
Pregunta <|.. MultipleChoiceClasico
Pregunta <|.. MultipleChoiceParcial
Pregunta <|.. MultipleChoicePenalidad
Pregunta <|.. OrderedChoice
Pregunta <|.. GroupChoice

RespuestaElegida -> Jugador


Jugador "2..5 "--"1 " Panel
Jugador .> ModficadorDePuntaje


VerdaderoFalsoPenalidad .. PenalizacionPregunta
MultipleChoicePenalidad.. PenalizacionPregunta

@enduml