@startuml
'https://plantuml.com/class-diagram

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

class Copien {
+ Esto(https://code-with-me.global.jetbrains.com/GMV7YyWgXO5tNo6j46eg9g#p=IU&fp=EB4B7C27C0EFAD9CC829C975B5D1B372000C6AF97E8924392A87283ED5C2100C&newUi=true)
}
@enduml